#!/usr/bin/env python
# coding: utf-8

# # Reference by Array Slice
# * Array generated by slicing is "reference"
#     * Since slicing is a pass-by-reference operation, values are interlocked with each other.
#     * Explicitly copy the value to copy() method to create it as a pass-by-value.
#     * Indexing returns an immutable object, so it does not affect the original.

# In[1]:


import numpy as np


# In[3]:


x = np.arange(10)
slice = x[:4]
slice[2] = 100 # x[2] become 100
x


# In[8]:


x = np.arange(10)
x_copy = x[:4].copy()
x_copy[2] = 100 # x not changed
x_copy, x


# In[ ]:




